export const practiceTests = [
    {
        id: 'p1',
        level: 'N5',
        type: 'vocabulary',
        title: 'Luyện tập Từ vựng N5 - Bài 1',
        time: 15,
        questions: [
            {
                id: 'q1',
                text: '（ ）を あけて ください。',
                options: ['まど', 'ドア', 'つくえ', 'いす'],
                correct: 0,
                explanation: 'まど (Mado) nghĩa là cửa sổ. "Hãy mở cửa sổ".',
            },
            {
                id: 'q2',
                text: 'あしたは （ ）に いきます。',
                options: ['がっこう', 'べんきょう', 'えんぴつ', 'しんぶん'],
                correct: 0,
                explanation: 'がっこう (Gakkou) nghĩa là trường học. "Ngày mai tôi sẽ đi đến trường".',
            },
            {
                id: 'q3',
                text: 'この りんごは （ ）です。',
                options: ['おいしい', 'あおい', 'きれい', 'にぎやか'],
                correct: 0,
                explanation: 'おいしい (Oishii) nghĩa là ngon. "Quả táo này ngon".',
            },
            {
                id: 'q4',
                text: 'きのう （ ）を かきました。',
                options: ['てがみ', 'テレビ', 'ラジオ', 'かばん'],
                correct: 0,
                explanation: 'てがみ (Tegami) nghĩa là thư. "Hôm qua tôi đã viết một bức thư".',
            },
            {
                id: 'q5',
                text: 'いっしょに （ ）を たべませんか。',
                options: ['ごはん', 'おんがく', 'しゃしん', 'でんわ'],
                correct: 0,
                explanation: 'ごはん (Gohan) nghĩa là cơm/bữa ăn. "Bạn có muốn ăn cơm cùng nhau không?".',
            },
            {
                id: 'q6',
                text: 'ちょっと （ ）を かしてください。',
                options: ['ペン', 'ノート', 'カサ', 'ボウル'],
                correct: 0,
                explanation: 'ペン (Pen) nghĩa là bút. "Hãy cho tôi mượn bút một chút".',
            },
            {
                id: 'q7',
                text: 'わたしの うちには （ ）が います。',
                options: ['いぬ', 'くるま', 'じてんしゃ', 'とけい'],
                correct: 0,
                explanation: 'いぬ (Inu) nghĩa là con chó. "Ở nhà tôi có một con chó".',
            },
            {
                id: 'q8',
                text: '（ ）を ききます。',
                options: ['おんがく', 'えいが', 'スポーツ', 'しんぶん'],
                correct: 0,
                explanation: 'おんがく (Ongaku) nghĩa là âm nhạc. "Nghe nhạc".',
            },
            {
                id: 'q9',
                text: 'デパートで （ ）を かいました。',
                options: ['くつ', 'およぎ', 'さんぽ', 'きっさてん'],
                correct: 0,
                explanation: 'くつ (Kutsu) nghĩa là giày. "Tôi đã mua giày ở trung tâm thương mại".',
            },
            {
                id: 'q10',
                text: '（ ）が たくさん あります。',
                options: ['き', 'みず', 'あつい', 'あまい'],
                correct: 0,
                explanation: 'き (Ki) nghĩa là cây. "Có rất nhiều cây".',
            },
        ],
    },
];
